server:
  port: 8763

spring:
  application:
    name: service-provider

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

batman:
  swagger:
    title: api manage RESTful Content APIs
    description: <font color="red">开发文档</font>
    version: 1.0
    modules:
    - {
      model-name: provider,
      packages: ["com.batman.provider.controller"],
      group-name: provider
    }